// Language translation constants for AI summary validation and cleaning

export const FORBIDDEN_ENGLISH_WORDS = [
    'delivers', 'thought-provoking', 'science', 'providing', 'readers',
    'insights', 'analysis', 'work', 'page', 'pages', 'book', 'author',
    'explores', 'concepts', 'theories', 'development', 'essential',
    'comprehensive', 'demonstrates', 'practical', 'application',

    'offers', 'perspectives', 'methodologies', 'esperado', 'nuevo',
    'the', 'text', 'scientific', 'and', 'that', 'with', 'for',
    'unknown', 'publisher', 'is', 'a', 'of', 'in', 'to', 'on',

    'presents', 'understanding', 'through', 'exploring', 'approach',
    'examining', 'within', 'field', 'various', 'different', 'important',
    'study', 'studies', 'research', 'methods', 'technique', 'techniques',
    'process', 'processes', 'system', 'systems', 'theory', 'practice',
    'knowledge', 'information', 'data', 'results', 'findings',
    'conclusion', 'conclusions', 'discussion', 'chapter', 'chapters',
    'section', 'sections', 'part', 'parts', 'overview', 'introduction',
    'summary', 'review', 'examination', 'investigation', 'consideration'
] as const;

export const LANGUAGE_REPLACEMENTS: Record<string, Record<string, string>> = {
    'es': {
        'delivers': 'ofrece',
        'thought-provoking': 'reflexivo',
        'science': 'ciencia',
        'providing': 'proporcionando',
        'readers': 'lectores',
        'insights': 'perspectivas',
        'analysis': 'análisis',
        'work': 'obra',
        'page': 'página',
        'pages': 'páginas',
        'book': 'libro',
        'author': 'autor',
        'explores': 'explora',
        'concepts': 'conceptos',
        'theories': 'teorías',
        'development': 'desarrollo',
        'essential': 'esencial',
        'comprehensive': 'exhaustivo',
        'demonstrates': 'demuestra',
        'practical': 'práctico',
        'application': 'aplicación',

        'offers': 'ofrece',
        'perspectives': 'perspectivas',
        'methodologies': 'metodologías',
        'the': 'el',
        'text': 'texto',
        'scientific': 'científico',
        'and': 'y',
        'that': 'que',
        'with': 'con',
        'for': 'para',
        'to': 'a',
        'on': 'en',
        'is': 'es',
        'a': 'un',
        'of': 'de',
        'in': 'en',

        'presents': 'presenta',
        'understanding': 'comprensión',
        'through': 'a través de',
        'exploring': 'explorando',
        'approach': 'enfoque',
        'examining': 'examinando',
        'within': 'dentro de',
        'field': 'campo',
        'various': 'varios',
        'different': 'diferentes',
        'important': 'importante',
        'study': 'estudio',
        'studies': 'estudios',
        'research': 'investigación',
        'methods': 'métodos',
        'technique': 'técnica',
        'techniques': 'técnicas',
        'process': 'proceso',
        'processes': 'procesos',
        'system': 'sistema',
        'systems': 'sistemas',
        'theory': 'teoría',
        'practice': 'práctica',
        'knowledge': 'conocimiento',
        'information': 'información',
        'data': 'datos',
        'results': 'resultados',
        'findings': 'hallazgos',
        'conclusion': 'conclusión',
        'conclusions': 'conclusiones',
        'discussion': 'discusión',
        'chapter': 'capítulo',
        'chapters': 'capítulos',
        'section': 'sección',
        'sections': 'secciones',
        'part': 'parte',
        'parts': 'partes',
        'overview': 'visión general',
        'introduction': 'introducción',
        'summary': 'resumen',
        'review': 'revisión',
        'examination': 'examen',
        'investigation': 'investigación',
        'consideration': 'consideración',
        'unknown': 'desconocido',
        'publisher': 'editorial'
    },
    'fr': {
        'delivers': 'offre',
        'thought-provoking': 'stimulant',
        'science': 'science',
        'providing': 'fournissant',
        'readers': 'lecteurs',
        'insights': 'perspectives',
        'analysis': 'analyse',
        'work': 'œuvre',
        'page': 'page',
        'pages': 'pages',
        'book': 'livre',
        'author': 'auteur',
        'explores': 'explore',
        'concepts': 'concepts',
        'theories': 'théories',
        'development': 'développement',
        'essential': 'essentiel',
        'comprehensive': 'complet',
        'demonstrates': 'démontre',
        'practical': 'pratique',
        'application': 'application'
    },
    'de': {
        'delivers': 'bietet',
        'thought-provoking': 'nachdenklich',
        'science': 'Wissenschaft',
        'providing': 'bereitstellend',
        'readers': 'Leser',
        'insights': 'Einblicke',
        'analysis': 'Analyse',
        'work': 'Werk',
        'page': 'Seite',
        'pages': 'Seiten',
        'book': 'Buch',
        'author': 'Autor',
        'explores': 'erforscht',
        'concepts': 'Konzepte',
        'theories': 'Theorien',
        'development': 'Entwicklung',
        'essential': 'wesentlich',
        'comprehensive': 'umfassend',
        'demonstrates': 'demonstriert',
        'practical': 'praktisch',
        'application': 'Anwendung'
    },
    'pt': {
        'delivers': 'oferece',
        'thought-provoking': 'reflexivo',
        'science': 'ciência',
        'providing': 'fornecendo',
        'readers': 'leitores',
        'insights': 'perspectivas',
        'analysis': 'análise',
        'work': 'obra',
        'page': 'página',
        'pages': 'páginas',
        'book': 'livro',
        'author': 'autor',
        'explores': 'explora',
        'concepts': 'conceitos',
        'theories': 'teorias',
        'development': 'desenvolvimento',
        'essential': 'essencial',
        'comprehensive': 'abrangente',
        'demonstrates': 'demonstra',
        'practical': 'prático',
        'application': 'aplicação',
        'offers': 'oferece',
        'perspectives': 'perspectivas',
        'methodologies': 'metodologias',
        'the': 'o',
        'text': 'texto',
        'scientific': 'científico',
        'and': 'e',
        'that': 'que',
        'with': 'com',
        'for': 'para',
        'to': 'para',
        'on': 'em',
        'is': 'é',
        'a': 'um',
        'of': 'de',
        'in': 'em',
        'presents': 'apresenta',
        'understanding': 'compreensão',
        'through': 'através de',
        'exploring': 'explorando',
        'approach': 'abordagem',
        'examining': 'examinando',
        'within': 'dentro de',
        'field': 'campo',
        'various': 'vários',
        'different': 'diversos',
        'important': 'importante',
        'study': 'estudo',
        'studies': 'estudos',
        'research': 'pesquisa',
        'methods': 'métodos',
        'technique': 'técnica',
        'techniques': 'técnicas',
        'process': 'processo',
        'processes': 'processos',
        'system': 'sistema',
        'systems': 'sistemas',
        'theory': 'teoria',
        'practice': 'prática',
        'knowledge': 'conhecimento',
        'information': 'informação',
        'unknown': 'desconhecido',
        'publisher': 'editora'
    },
    'it': {
        'delivers': 'offre',
        'thought-provoking': 'stimolante',
        'science': 'scienza',
        'providing': 'fornendo',
        'readers': 'lettori',
        'insights': 'prospettive',
        'analysis': 'analisi',
        'work': 'opera',
        'page': 'pagina',
        'pages': 'pagine',
        'book': 'libro',
        'author': 'autore',
        'explores': 'esplora',
        'concepts': 'concetti',
        'theories': 'teorie',
        'development': 'sviluppo',
        'essential': 'essenziale',
        'comprehensive': 'completo',
        'demonstrates': 'dimostra',
        'practical': 'pratico',
        'application': 'applicazione',
        'offers': 'offre',
        'perspectives': 'prospettive',
        'methodologies': 'metodologie',
        'the': 'il',
        'text': 'testo',
        'scientific': 'scientifico',
        'and': 'e',
        'that': 'che',
        'with': 'con',
        'for': 'per',
        'to': 'a',
        'on': 'su',
        'is': 'è',
        'a': 'un',
        'of': 'di',
        'in': 'in',
        'presents': 'presenta',
        'understanding': 'comprensione',
        'through': 'attraverso',
        'exploring': 'esplorando',
        'approach': 'approccio',
        'examining': 'esaminando',
        'within': 'dentro',
        'field': 'campo',
        'various': 'vari',
        'different': 'diversi',
        'important': 'importante',
        'study': 'studio',
        'studies': 'studi',
        'research': 'ricerca',
        'methods': 'metodi',
        'technique': 'tecnica',
        'techniques': 'tecniche',
        'process': 'processo',
        'processes': 'processi',
        'system': 'sistema',
        'systems': 'sistemi',
        'theory': 'teoria',
        'practice': 'pratica',
        'knowledge': 'conoscenza',
        'information': 'informazione',
        'unknown': 'sconosciuto',
        'publisher': 'editore'
    }
};

// Language-specific phrase patterns for more natural translations
export const LANGUAGE_PHRASE_PATTERNS: Record<string, Record<string, string>> = {
    'es': {
        'delivers a thought-provoking science': 'ofrece una ciencia reflexiva',
        'provides? readers with': 'proporciona a los lectores',
        'essential insights and analysis': 'perspectivas y análisis esenciales',
        'The text offers': 'El texto ofrece',
        'scientific perspectives': 'perspectivas científicas',
        'presents a comprehensive understanding': 'presenta una comprensión exhaustiva',
        'through exploring various concepts': 'explorando varios conceptos',
        'within the field': 'dentro del campo',
        'different approaches': 'diferentes enfoques',
        'examining important theories': 'examinando teorías importantes',
        'research methods': 'métodos de investigación',
        'practical techniques': 'técnicas prácticas'
    },
    'pt': {
        'delivers a thought-provoking science': 'oferece uma ciência reflexiva',
        'provides? readers with': 'fornece aos leitores',
        'essential insights and analysis': 'perspectivas e análises essenciais',
        'The text offers': 'O texto oferece',
        'scientific perspectives': 'perspectivas científicas',
        'presents a comprehensive understanding': 'apresenta uma compreensão abrangente',
        'through exploring various concepts': 'explorando vários conceitos',
        'within the field': 'dentro do campo',
        'different approaches': 'diferentes abordagens',
        'examining important theories': 'examinando teorias importantes',
        'research methods': 'métodos de pesquisa',
        'practical techniques': 'técnicas práticas'
    },
    'it': {
        'delivers a thought-provoking science': 'offre una scienza stimolante',
        'provides? readers with': 'fornisce ai lettori',
        'essential insights and analysis': 'prospettive e analisi essenziali',
        'The text offers': 'Il testo offre',
        'scientific perspectives': 'prospettive scientifiche',
        'presents a comprehensive understanding': 'presenta una comprensione completa',
        'through exploring various concepts': 'esplorando vari concetti',
        'within the field': 'nel campo',
        'different approaches': 'diversi approcci',
        'examining important theories': 'esaminando teorie importanti',
        'research methods': 'metodi di ricerca',
        'practical techniques': 'tecniche pratiche'
    }
};

// Individual word patterns for aggressive replacement
export const LANGUAGE_WORD_PATTERNS: Record<string, Record<string, string>> = {
    'es': {
        'science': 'ciencia',
        'scientific': 'científico',
        'research': 'investigación',
        'methods': 'métodos',
        'techniques': 'técnicas',
        'approach': 'enfoque',
        'approaches': 'enfoques',
        'theories': 'teorías',
        'theory': 'teoría',
        'concepts': 'conceptos',
        'concept': 'concepto',
        'understanding': 'comprensión',
        'knowledge': 'conocimiento',
        'information': 'información',
        'analysis': 'análisis',
        'studies': 'estudios',
        'study': 'estudio',
        'field': 'campo',
        'practical': 'práctico',
        'process': 'proceso',
        'system': 'sistema',
        'work': 'obra'
    },
    'pt': {
        'science': 'ciência',
        'scientific': 'científico',
        'research': 'pesquisa',
        'methods': 'métodos',
        'techniques': 'técnicas',
        'approach': 'abordagem',
        'approaches': 'abordagens',
        'theories': 'teorias',
        'theory': 'teoria',
        'concepts': 'conceitos',
        'concept': 'conceito',
        'understanding': 'compreensão',
        'knowledge': 'conhecimento',
        'information': 'informação',
        'analysis': 'análise',
        'studies': 'estudos',
        'study': 'estudo',
        'field': 'campo',
        'practical': 'prático',
        'process': 'processo',
        'system': 'sistema',
        'work': 'obra'
    },
    'it': {
        'science': 'scienza',
        'scientific': 'scientifico',
        'research': 'ricerca',
        'methods': 'metodi',
        'techniques': 'tecniche',
        'approach': 'approccio',
        'approaches': 'approcci',
        'theories': 'teorie',
        'theory': 'teoria',
        'concepts': 'concetti',
        'concept': 'concetto',
        'understanding': 'comprensione',
        'knowledge': 'conoscenza',
        'information': 'informazione',
        'analysis': 'analisi',
        'studies': 'studi',
        'study': 'studio',
        'field': 'campo',
        'practical': 'pratico',
        'process': 'processo',
        'system': 'sistema',
        'work': 'opera'
    }
};
